import Head from 'next/head'
import useSWR from 'swr'
import axios from 'axios';
import Code from '@components/Code';
import Navbar from '@components/Navbar';
import Link from 'next/link';

const fetcher = url => axios.get(url).then(res => res.data)

export default function Blog() {

  const { data, error } = useSWR('/api/blog', fetcher)

  if (error) return <div>failed to load</div>
  if (!data) return <div>loading...</div>

  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 class">
          <h1 className="dark:text-white text-2xl font-semibold pb-4">Blog</h1>
          <ul>
            {data.map((item, index) =>
              <li key={item.id}>
                <Link href={`blog/detail/${item.id}`}>
                  <a className="text-blue-500 hover:text-blue-600 transition-all text-sm font-medium">{index + 1} - {item.title}</a>
                </Link>
              </li>
            )}
          </ul>

          <Code name="pages/blog" code={`import useSWR from 'swr'
import axios from 'axios';

const fetcher = url => axios.get(url).then(res => res.data)

export default function Blog() {

  const { data, error } = useSWR('/api/blog', fetcher)

  if (error) return <div>failed to load</div>
  if (!data) return <div>loading...</div>

  return (
    <ul>
      {data.map((item, index) =>
        <li key={item.id}>
          <Link href={'blog/detail/$(item.id)'}>
            <a className="text-blue-500 hover:text-blue-600 transition-all text-sm font-medium">{index + 1} - {item.title}</a>
          </Link>
        </li>
      )}
    </ul>
  )
}`} />
        </div>
      </main >
    </>
  )
}
