import { useState, useEffect } from 'react'
import Head from 'next/head'
import useSWR from 'swr'
import Image from 'next/image';
import Code from '@components/Code';
import Navbar from '@components/Navbar';
import FullPageLoader from '@components/FullPageLoader';

const fetcher = (...args) => fetch(...args).then(res => res.json())

export default function Dependent() {
  const [name, setName] = useState(null)

  const { data: users, error: usersError } = useSWR('/api/users', fetcher)
  const { data: vercel, error: vercelError } = useSWR(name ? `/api/users/${name}` : null, fetcher)

  useEffect(() => {
    if (users) {
      setName(users[0].id)
    }
  }, [users])

  if (usersError) return <div>failed to load all users</div>
  if (vercelError) return <div>failed to load vercel</div>
  if (!vercel) return <FullPageLoader />

  return (
    <>
      <Head>
        <title>Dependent</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 class">
          <h1 className="dark:text-white text-2xl font-semibold pb-4">Dependent</h1>
          <div className="border dark:border-neutral-700 p-4 rounded my-6">
            <a className="text-blue-500 hover:text-blue-600 transition-all cursor-pointer block mb-4" href={vercel.api} target="_blank" rel="noreferrer">{vercel.api}</a>
            <div className="space-y-1.5 dark:text-white">
              <div className="relative w-20 h-20 ">
                <Image alt="Image" className="rounded" layout="fill" src={vercel.image} />
              </div>
              <p>Name : {vercel.name}</p>
              <p>Bio : {vercel.bio}</p>
              <p>Type : {vercel.type}</p>
              <p>Public Repos : {vercel.repos}</p>
              <p>Blog : {vercel.blog ? <a className="text-blue-500 hover:text-blue-600 transition-all cursor-pointer" href={vercel.blog} target="_blank" rel="noreferrer">{vercel.blog}</a> : "-"}</p>
              <p>Location : {vercel.location}</p>
              <p>Email : {vercel.email ? <a className="text-blue-500 hover:text-blue-600 transition-all cursor-pointer" href={`mailto:${vercel.email}`} target="_blank" rel="noreferrer">{vercel.email}</a> : "-"}</p>
            </div>
          </div>
          <Code name="pages/dependent" code={`import { useState, useEffect } from 'react'
import useSWR from 'swr'
import FullPageLoader from '@components/FullPageLoader';

const fetcher = (...args) => fetch(...args).then(res => res.json())

export default function Dependent() {
  const [name, setName] = useState(null)

  const { data: users, error: usersError } = useSWR('/api/users', fetcher)
  const { data: vercel, error: vercelError } = useSWR(name ? '/api/users/\${name}' : null, fetcher)

  useEffect(() => {
    if (users) {
      setName(users[0].id)
    }
  }, [users])

  if (usersError) return <div>failed to load all users</div>
  if (vercelError) return <div>failed to load vercel</div>
  if (!vercel) return <FullPageLoader />

  return (
    <Image alt="Image" src={vercel.image} />
    <p>Name : {vercel.name}</p>
    <p>Bio : {vercel.bio}</p>
    <p>Type : {vercel.type}</p>
    <p>Public Repos : {vercel.repos}</p>
    <p>Blog : {vercel.blog}</p>
    <p>Location : {vercel.location}</p>
    <p>Email : {vercel.email}</p>
  )
}`} />
        </div>
      </main >
    </>
  )
}
