import { useState, useEffect } from 'react';
import Head from 'next/head';
import useSWR, { useSWRConfig } from 'swr'
import Image from 'next/image';
import axios from 'axios';
import Code from '@components/Code';
import Navbar from '@components/Navbar';
import Skeletons from '@components/Skeletons';

export default function NoToken() {
  const { mutate } = useSWRConfig()
  const [token, setToken] = useState(null)
  
  const config = {
    headers: {
      Authorization: `Bearer ${token}`,
    },
  };

  const fetcher = url => axios.get(url, config).then(res => res.data)
  const { data, error } = useSWR('/api/token', fetcher)

  useEffect(() => {
    mutate('/api/token')
  },[token])

  return (
    <>
      <Head>
        <title>Using Axios with No Token Provided</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 class">
          <h1 className="dark:text-white text-2xl font-semibold pb-4">Using Axios with No Token Provided</h1>

            <p className="dark:text-white mb-2">Token : <span className="font-medium">{token ? token : "invalid-token"}</span></p>
          <div className="flex items-center space-x-3  mb-4">
            <button onClick={() => setToken("valid-token")} className="bg-blue-500 hover:bg-blue-600 py-1 px-2 text-sm font-medium text-white rounded">Set Token</button>
            <button onClick={() => setToken(null)} className="bg-red-500 hover:bg-red-600 py-1 px-2 text-sm font-medium text-white rounded">Remove Token</button>
          </div>

          {error && <p className="text-red-500 mb-2 font-medium">Error : {error?.response.data.error}</p>}

          {data && !error ?
            <div className="border dark:border-neutral-700 p-4 rounded my-6">
              <a className="text-blue-500 hover:text-blue-600 transition-all cursor-pointer block mb-4" href={data.api} target="_blank" rel="noreferrer">{data.api}</a>
              <div className="space-y-1.5 dark:text-white">
                <div className="relative w-20 h-20 ">
                  <Image alt="Image" className="rounded" layout="fill" src={data.image} />
                </div>
                <p>Name : {data.name}</p>
                <p>Bio : {data.bio}</p>
                <p>Type : {data.type}</p>
                <p>Public Repos : {data.repos}</p>
                <p>Blog : {data.blog ? <a className="text-blue-500 hover:text-blue-600 transition-all cursor-pointer" href={data.blog} target="_blank" rel="noreferrer">{data.blog}</a> : "-"}</p>
                <p>Location : {data.location}</p>
                <p>Email : {data.email ? <a className="text-blue-500 hover:text-blue-600 transition-all cursor-pointer" href={`mailto:${data.email}`} target="_blank" rel="noreferrer">{data.email}</a> : "-"}</p>
              </div>
            </div>
            :
            <Skeletons className="!h-32" />
          }

          <Code name="pages/api/token" code={`import { users } from "@data/users"

export default function handler(req, res) {
  const { method } = req;
  switch (method) {
    case "GET":
      if (!req.headers.authorization) {
        return res.status(422).json({ error: "Please provide headers" });
      }
      const token = req.headers.authorization.split("Bearer ")[1];
      if (!token) {
        return res.status(422).json({ error: "Token not found" });
      }
      if (token !== 'valid-token') {
        return res.status(422).json({ error: "Token not valid" });
      }
      return res.status(200).json(users[8])
    default:
      return res.json({ error: "Only accepting GET method" });
  }
}`} />
          <Code name="pages/no-token" code={`import { useState, useEffect } from 'react';
import useSWR, { useSWRConfig } from 'swr'
import axios from 'axios';
import Skeletons from '@components/Skeletons';

export default function NoToken() {
  const { mutate } = useSWRConfig()
  const [token, setToken] = useState(null)
  
  const config = {
    headers: {
      Authorization: 'Bearer \${token}',
    },
  };

  const fetcher = url => axios.get(url, config).then(res => res.data)
  const { data, error } = useSWR('/api/token', fetcher)

  useEffect(() => {
    mutate('/api/token')
  },[token])

  return (
    <>
      <p>Set or Remove Token, then wait few second</p>
      <div>
        <p>Token : <span>{token ? token : "invalid-token"}</span></p>
        <button onClick={() => setToken("valid-token")}>Set Token</button>
        <button onClick={() => setToken(null)}>Remove Token</button>
      </div>

      {error && <p>Error : {error?.response.data.error}</p>}

      {data && !error ?
        <Image alt="Image" src={data.image} />
        <p>Name : {data.name}</p>
        <p>Bio : {data.bio}</p>
        <p>Type : {data.type}</p>
        <p>Public Repos : {data.repos}</p>
        <p>Blog : {data.blog}</p>
        <p>Location : {data.location}</p>
        <p>Email : {data.email}</p>
        :
        <Skeletons className="!h-32" />
      }
    </>
  )
}`} />
        </div>
      </main >
    </>
  )
}
