import { useState } from 'react'
import Head from 'next/head'
import useSWR from 'swr'
import Code from '@components/Code';
import Navbar from '@components/Navbar';
import Skeletons from '@components/Skeletons';

const fetcher = (...args) => fetch(...args).then(res => res.json())

export default function Pagination() {
  const [page, setPage] = useState(1);

  const { data: posts, error } = useSWR(`https://jsonplaceholder.typicode.com/posts?_page=${page}`, fetcher)

  function handlePrev() {
    if (page > 1) setPage(page - 1)
  }

  function handleNext() {
    if (page < 10) setPage(page + 1)
  }

  if (error) return <div>failed to load</div>

  return (
    <>
      <Head>
        <title>Pagination SWR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 class">
          <h1 className="dark:text-white text-2xl font-semibold pb-4">Pagination SWR</h1>
          <h2 className="dark:text-white text-xl font-semibold">Blog Post</h2>
          <a className="text-blue-500 hover:text-blue-600 transition-all cursor-pointer block mb-4"
            href={`https://jsonplaceholder.typicode.com/posts?_page=${page}`} target="_blank"
            rel="noreferrer">https://jsonplaceholder.typicode.com/posts?_page={page}</a>
          {posts ?
            <ol className="space-y-2 list-inside my-4 dark:text-gray-200">
              {posts?.map(post => (
                <li key={post.id}>{post.id}. {post.title}</li>
              ))}
            </ol>
            :
            <>
              <Skeletons />
              <Skeletons />
              <Skeletons />
              <Skeletons />
              <Skeletons />
              <Skeletons />
              <Skeletons />
            </>
          }
          <button onClick={handlePrev} disabled={page === 1} className={`${page === 1 && 'cursor-not-allowed'} mt-2 mr-2 bg-blue-500 hover:bg-blue-600 py-1 px-2 text-sm font-medium text-white rounded`}>
            Prev
          </button>
          <span className="mx-2 dark:text-white">Page : {page}</span>
          <button onClick={handleNext} disabled={page === 10} className={`${page === 10 && 'cursor-not-allowed'} mt-2 bg-blue-500 hover:bg-blue-600 py-1 px-2 text-sm font-medium text-white rounded`}>
            Next
          </button>

          <Code name="pages/pagination" code={`import { useState } from 'react'
import useSWR from 'swr'
import Skeletons from '@components/Skeletons';

const fetcher = (...args) => fetch(...args).then(res => res.json())

export default function Pagination() {
  const [page, setPage] = useState(1);

  const { data: posts, error } = useSWR('https://jsonplaceholder.typicode.com/posts?_page=\${page}', fetcher)

  function handlePrev() {
    if (page > 1) setPage(page - 1)
  }

  function handleNext() {
    if (page < 10) setPage(page + 1)
  }

  if (error) return <div>failed to load</div>

  return (
    {posts ?
      <ol>
        {posts?.map(post => (
          <li key={post.id}>{post.id}. {post.title}</li>
        ))}
      </ol>
      :
      <Skeletons />
    }
    <button onClick={handlePrev} disabled={page === 1} className={'$\{page === 1 && 'cursor-not-allowed'}'}>
      Prev
    </button>
    <span>Page : {page}</span>
    <button onClick={handleNext} disabled={page === 10} className={'\${page === 10 && 'cursor-not-allowed'}'}>
      Next
    </button>
  )
}`} />
        </div>
      </main >
    </>
  )
}
