import { useState, useEffect } from 'react';
import Head from 'next/head'
import useSWR from "swr";
import Image from 'next/image';
import Code from '@components/Code';
import Navbar from '@components/Navbar';
import Skeletons from '@components/Skeletons';

const fetcher = (url) => fetch(url).then(res => res.json())

export default function State() {
  const [repos, setRepos] = useState()
  const [upperCase, setUpperCase] = useState(true)
  const { data, error } = useSWR('/api/repos/vue', fetcher)

  useEffect(() => {
    if (data) setRepos(data);
  }, [data])

  if (error) return <div>failed to load</div>

  function handleUppercase() {
    if (upperCase) setRepos({ ...repos, 
      name: repos.name.toUpperCase(), 
      full_name: repos.full_name.toUpperCase(), 
      language: repos.language.toUpperCase()
    })
    else setRepos({ ...repos, 
      name: repos.name.toLowerCase(), 
      full_name: repos.full_name.toLowerCase(),
      language: repos.language.toLowerCase()
    })
    setUpperCase(!upperCase)
  }

  return (
    <>
      <Head>
        <title>SWR to useState</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 class">
          <h1 className="dark:text-white text-2xl font-semibold pb-4">SWR to useState</h1>
          <div className="border dark:border-neutral-700 p-4 rounded my-6">
            <a className="text-blue-500 hover:text-blue-600 transition-all cursor-pointer block mb-4 break-all" href="https://api.github.com/repos/vuejs/vue" target="_blank" rel="noreferrer">https://api.github.com/repos/vuejs/vue</a>

            {repos ?
              <div className="space-y-1.5 dark:text-white">
                <div className="relative w-20 h-20 mb-2">
                  <Image alt="Image" className="rounded" layout="fill" src={repos.image} />
                </div>
                <p>Name : {repos.name}
                  <button onClick={handleUppercase} className="text-xs text-white bg-blue-500 hover:bg-blue-600 transition-all rounded py-1 px-1.5 ml-2">
                    {upperCase ? "Uppercase" : "Lowercase"}
                  </button>
                </p>
                <p>Full Name : {repos.full_name}</p>
                <p>Language : {repos.language}</p>
                <p>Homepage : {repos.homepage ? <a className="text-blue-500 hover:text-blue-600 transition-all cursor-pointer" href={repos.homepage} target="_blank" rel="noreferrer">{repos.homepage}</a> : "-"}</p>
                <p>Description : {repos.description}</p>
                <p>Repo URL : {repos.repo_url ? <a className="text-blue-500 hover:text-blue-600 transition-all cursor-pointer" href={repos.repo_url} target="_blank" rel="noreferrer">{repos.repo_url}</a> : "-"}</p>
                <p>License : {repos.license}</p>
                <p>Owner : {repos.owner}</p>
                <p>Owner URL : {repos.owner_url ? <a className="text-blue-500 hover:text-blue-600 transition-all cursor-pointer" href={repos.owner_url} target="_blank" rel="noreferrer">{repos.owner_url}</a> : "-"}</p>
              </div>
              :
              <Skeletons className="!h-32" />
            }

          </div>
          <Code name="pages/state" code={`import { useState, useEffect } from 'react';
import useSWR from "swr";
import Skeletons from '@components/Skeletons';

const fetcher = (url) => fetch(url).then(res => res.json())

export default function State() {
  const [repos, setRepos] = useState()
  const [upperCase, setUpperCase] = useState(true)
  const { data, error } = useSWR('/api/repos/vue', fetcher)

  useEffect(() => {
    if (data) setRepos(data);
  }, [data])

  if (error) return <div>failed to load</div>

  function handleUppercase() {
    if (upperCase) setRepos({ ...repos, 
      name: repos.name.toUpperCase(), 
      full_name: repos.full_name.toUpperCase(), 
      language: repos.language.toUpperCase()
    })
    else setRepos({ ...repos, 
      name: repos.name.toLowerCase(), 
      full_name: repos.full_name.toLowerCase(),
      language: repos.language.toLowerCase()
    })
    setUpperCase(!upperCase)
  }

  return (
    {repos ?
      <div>
        <Image alt="Image" src={repos.image} />
        <p>Name : {repos.name}
          <button onClick={handleUppercase}>
            {upperCase ? "Uppercase" : "Lowercase"}
          </button>
        </p>
        <p>Full Name : {repos.full_name}</p>
        <p>Language : {repos.language}</p>
        <p>Homepage : {repos.homepage}</p>
        <p>Description : {repos.description}</p>
        <p>Repo URL : {repos.repo_url}</p>
        <p>License : {repos.license}</p>
        <p>Owner : {repos.owner}</p>
        <p>Owner URL : {repos.owner_url}</p>
      </div>
      :
      <Skeletons />
    }
  )
}`} />
        </div>
      </main >
    </>
  )
}
