import Head from 'next/head'
import useSWR from 'swr'
import Image from 'next/image';
import axios from 'axios';
import Code from '@components/Code';
import Navbar from '@components/Navbar';
import Skeletons from '@components/Skeletons';

const config = {
  headers: {
    Authorization: `Bearer valid-token`,
  },
};
const fetcher = url => axios.get(url, config).then(res => res.data)

export default function Token() {

  const { data, error } = useSWR('/api/data', fetcher)

  if (error) return <div>{error.response.data.error}</div>

  return (
    <>
      <Head>
        <title>Using Axios with Token</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 class">
          <h1 className="dark:text-white text-2xl font-semibold pb-4">Using Axios with Token</h1>

          {data ?
            <div className="border dark:border-neutral-700 p-4 rounded my-6">
              <a className="text-blue-500 hover:text-blue-600 transition-all cursor-pointer block mb-4" href={data.api} target="_blank" rel="noreferrer">{data.api}</a>
              <div className="space-y-1.5 dark:text-white">
                <div className="relative w-20 h-20 ">
                  <Image alt="Image" className="rounded" layout="fill" src={data.image} />
                </div>
                <p>Name : {data.name}</p>
                <p>Bio : {data.bio}</p>
                <p>Type : {data.type}</p>
                <p>Public Repos : {data.repos}</p>
                <p>Blog : {data.blog ? <a className="text-blue-500 hover:text-blue-600 transition-all cursor-pointer" href={data.blog} target="_blank" rel="noreferrer">{data.blog}</a> : "-"}</p>
                <p>Location : {data.location}</p>
                <p>Email : {data.email ? <a className="text-blue-500 hover:text-blue-600 transition-all cursor-pointer" href={`mailto:${data.email}`} target="_blank" rel="noreferrer">{data.email}</a> : "-"}</p>
              </div>
            </div>
            :
            <Skeletons className="!h-32" />
          }

          <Code name="pages/api/data" code={`import { users } from "@data/users"

export default function handler(req, res) {
  const { method } = req;
  switch (method) {
    case "GET":
      if (!req.headers.authorization) {
        return res.status(422).json({ error: "Please provide headers" });
      }
      const token = req.headers.authorization.split("Bearer ")[1];
      if (!token) {
        return res.status(422).json({ error: "Token not found" });
      }
      if (token !== 'valid-token') {
        return res.status(422).json({ error: "Token not valid" });
      }
      return res.status(200).json(users[6])
    default:
      return res.json({ error: "Only accepting GET method" });
  }
}`} />
          <Code name="pages/token" code={`import useSWR from 'swr'
import axios from 'axios';

const config = {
  headers: {
    Authorization: 'Bearer valid-token',
  },
};
const fetcher = url => axios.get(url, config).then(res => res.data)

export default function Token() {

  const { data, error } = useSWR('/api/data', fetcher)

  if (error) return <div>{error.response.data.error}</div>

  return (
    <>
      {data ? 
        <Image alt="Image" src={data.image} />
        <p>Name : {data.name}</p>
        <p>Bio : {data.bio}</p>
        <p>Type : {data.type}</p>
        <p>Public Repos : {data.repos}</p>
        <p>Blog : {data.blog}</p>
        <p>Location : {data.location}</p>
        <p>Email : {data.email}</p>
        :
        <Skeletons />
      }
    </>
  )
}`} />
        </div>
      </main >
    </>
  )
}
