import Head from 'next/head'
import Image from 'next/image';
import Code from '@components/Code';
import Navbar from '@components/Navbar';
import FullPageLoader from '@components/FullPageLoader';
import { useGetRepo, useGetUser} from '@libs/useRequest';

export default function UseRequest() {

  const { data: repo, error: repoError } = useGetRepo('nuxtjs')
  const { data: user, error: userError } = useGetUser('svelte')

  if (repoError || userError) return <div>failed to load</div>
  if (!repo || !user) return <FullPageLoader />

  return (
    <>
      <Head>
        <title>Use Custom Request</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen pb-8">

        <Navbar />

        <div className="max-w-5xl px-4 mx-auto pt-4 class">
          <h1 className="dark:text-white text-2xl font-semibold pb-4">Use Custom Request</h1>
          <div className="border dark:border-neutral-700 p-4 rounded my-6">
            <div className="space-y-1.5 dark:text-white">
              <a className="text-blue-500 hover:text-blue-600 transition-all cursor-pointer block mb-4" href={repo.api} target="_blank" rel="noreferrer">{repo.api}</a>
              <div className="relative w-20 h-20 mb-2">
                <Image alt="Image" className="rounded" layout="fill" src={repo.image} />
              </div>
              <p>Name : {repo.name}</p>
              <p>Full Name : {repo.full_name}</p>
              <p>Language : {repo.language}</p>
              <p>Homepage : {repo.homepage ? <a className="text-blue-500 hover:text-blue-600 transition-all cursor-pointer" href={repo.homepage} target="_blank" rel="noreferrer">{repo.homepage}</a> : "-"}</p>
              <p>Description : {repo.description}</p>
              <p>Repo URL : {repo.repo_url ? <a className="text-blue-500 hover:text-blue-600 transition-all cursor-pointer" href={repo.repo_url} target="_blank" rel="noreferrer">{repo.repo_url}</a> : "-"}</p>
              <p>License : {repo.license}</p>
              <p>Owner : {repo.owner}</p>
              <p>Owner URL : {repo.owner_url ? <a className="text-blue-500 hover:text-blue-600 transition-all cursor-pointer" href={repo.owner_url} target="_blank" rel="noreferrer">{repo.owner_url}</a> : "-"}</p>
            </div>
          </div>
          <div className="border dark:border-neutral-700 p-4 rounded my-6">
            <a className="text-blue-500 hover:text-blue-600 transition-all cursor-pointer block mb-4" href={user.api} target="_blank" rel="noreferrer">{user.api}</a>
            <div className="space-y-1.5 dark:text-white">
              <div className="relative w-20 h-20 ">
                <Image alt="Image" className="rounded" layout="fill" src={user.image} />
              </div>
              <p>Name : {user.name}</p>
              <p>Bio : {user.bio}</p>
              <p>Type : {user.type}</p>
              <p>Public Repos : {user.repos}</p>
              <p>Blog : {user.blog ? <a className="text-blue-500 hover:text-blue-600 transition-all cursor-pointer" href={user.blog} target="_blank" rel="noreferrer">{user.blog}</a> : "-"}</p>
              <p>Location : {user.location}</p>
              <p>Email : {user.email ? <a className="text-blue-500 hover:text-blue-600 transition-all cursor-pointer" href={`mailto:${user.email}`} target="_blank" rel="noreferrer">{user.email}</a> : "-"}</p>
            </div>
          </div>
          <Code name="libs/useRequest" code={`import useSWR from "swr"

const fetcher = url => fetch(url).then(res => res.json())

export function useGetUser(name) {
  if (!name) {
    throw new Error("Name is required")
  }
  const { data, error } = useSWR('/api/users/\${name}', fetcher)
  return { data, error }
}

export function useGetRepo(name) {
  if (!name) {
    throw new Error("Name is required")
  }
  const { data, error } = useSWR('/api/repos/\${name}', fetcher)
  return { data, error }
}`} />
          <Code name="pages/use-request" code={`import FullPageLoader from '@components/FullPageLoader';
import { useGetRepo, useGetUser } from '@libs/useRequest';

export default function UseRequest() {

  const { data: repo, error: repoError } = useGetRepo('nuxtjs')
  const { data: user, error: userError } = useGetUser('svelte')

  if (repoError || userError) return <div>failed to load</div>
  if (!repo || !user) return <FullPageLoader />

  return (
    <>
      <div>
        <Image alt="Image" src={repo.image} />
        <p>Name : {repo.name}</p>
        <p>Full Name : {repo.full_name}</p>
        <p>Language : {repo.language}</p>
        <p>Homepage : {repo.homepage}</p>
        <p>Description : {repo.description}</p>
        <p>Repo URL : {repo.repo_url}</p>
        <p>License : {repo.license}</p>
        <p>Owner : {repo.owner}</p>
        <p>Owner URL : {repo.owner_url}</p>
      </div>
      <div>
        <Image alt="Image" src={user.image} />
        <p>Name : {user.name}</p>
        <p>Bio : {user.bio}</p>
        <p>Type : {user.type}</p>
        <p>Public Repos : {user.repos}</p>
        <p>Blog : {user.blog}</p>
        <p>Location : {user.location}</p>
        <p>Email : {user.email}</p>
      </div>
    </>
  )
}`} />
        </div>
      </main >
    </>
  )
}
